import { PostWithCategory } from "@/types/collections"
import { supabase } from "@/lib/utils"
import PostList from "@/components/post/post-list"

const Page = async () => {
  const { data: posts } = await supabase
    .from("posts")
    .select("*, category:categories(*)")
    .returns<PostWithCategory[]>()

  return (
    <section className="container grid items-center gap-6 pt-6 pb-8 md:py-10">
      <div className="flex max-w-[980px] flex-col items-start gap-2">
        <h1 className="text-2xl font-extrabold leading-tight tracking-tighter sm:text-2xl md:text-4xl lg:text-5xl">
          Posts
        </h1>
        <p className="max-w-[700px] text-lg text-muted-foreground sm:text-xl mb-5">
          All blog posts generated by AI.
        </p>
      </div>
      <PostList posts={posts ?? []} />
    </section>
  )
}

export default Page
